/* Generated By:JavaCC: Do not edit this line. StraightLineParserConstants.java */
package parser;

public interface StraightLineParserConstants {

  int EOF = 0;
  int SEMICOLON = 6;
  int ASSIGN = 7;
  int LPAREN = 8;
  int RPAREN = 9;
  int COMMA = 10;
  int PRINT = 11;
  int PLUS = 12;
  int MINUS = 13;
  int TIMES = 14;
  int DIVIDE = 15;
  int INTEGER_LITERAL = 16;
  int IDENTIFIER = 17;
  int LETTER = 18;
  int DIGIT = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\";\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"print\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
