//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> StmList()
    * f1 -> <EOF>
    */
   public void visit(Goal n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Stm()
    * f1 -> ( ";" Stm() )*
    */
   public void visit(StmList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Assignment()
    *       | PrintStm()
    */
   public void visit(Stm n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> WriteId()
    * f1 -> ":="
    * f2 -> Exp()
    */
   public void visit(Assignment n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(WriteId n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "print"
    * f1 -> "("
    * f2 -> ExpList()
    * f3 -> ")"
    */
   public void visit(PrintStm n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> Exp()
    * f1 -> ( AppendExp() )*
    */
   public void visit(ExpList n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ","
    * f1 -> Exp()
    */
   public void visit(AppendExp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> MulExp()
    * f1 -> ( PlusOp() | MinOp() )*
    */
   public void visit(Exp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "+"
    * f1 -> MulExp()
    */
   public void visit(PlusOp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "-"
    * f1 -> MulExp()
    */
   public void visit(MinOp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> PrimExp()
    * f1 -> ( MulOp() | DivOp() )*
    */
   public void visit(MulExp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "*"
    * f1 -> PrimExp()
    */
   public void visit(MulOp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "/"
    * f1 -> PrimExp()
    */
   public void visit(DivOp n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ReadId()
    *       | Num()
    *       | StmExp()
    */
   public void visit(PrimExp n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(ReadId n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(Num n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> StmList()
    * f2 -> ","
    * f3 -> Exp()
    * f4 -> ")"
    */
   public void visit(StmExp n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

}
