//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> StmList()
    * f1 -> <EOF>
    */
   public R visit(Goal n, A argu);

   /**
    * f0 -> Stm()
    * f1 -> ( ";" Stm() )*
    */
   public R visit(StmList n, A argu);

   /**
    * f0 -> Assignment()
    *       | PrintStm()
    */
   public R visit(Stm n, A argu);

   /**
    * f0 -> WriteId()
    * f1 -> ":="
    * f2 -> Exp()
    */
   public R visit(Assignment n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(WriteId n, A argu);

   /**
    * f0 -> "print"
    * f1 -> "("
    * f2 -> ExpList()
    * f3 -> ")"
    */
   public R visit(PrintStm n, A argu);

   /**
    * f0 -> Exp()
    * f1 -> ( AppendExp() )*
    */
   public R visit(ExpList n, A argu);

   /**
    * f0 -> ","
    * f1 -> Exp()
    */
   public R visit(AppendExp n, A argu);

   /**
    * f0 -> MulExp()
    * f1 -> ( PlusOp() | MinOp() )*
    */
   public R visit(Exp n, A argu);

   /**
    * f0 -> "+"
    * f1 -> MulExp()
    */
   public R visit(PlusOp n, A argu);

   /**
    * f0 -> "-"
    * f1 -> MulExp()
    */
   public R visit(MinOp n, A argu);

   /**
    * f0 -> PrimExp()
    * f1 -> ( MulOp() | DivOp() )*
    */
   public R visit(MulExp n, A argu);

   /**
    * f0 -> "*"
    * f1 -> PrimExp()
    */
   public R visit(MulOp n, A argu);

   /**
    * f0 -> "/"
    * f1 -> PrimExp()
    */
   public R visit(DivOp n, A argu);

   /**
    * f0 -> ReadId()
    *       | Num()
    *       | StmExp()
    */
   public R visit(PrimExp n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(ReadId n, A argu);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(Num n, A argu);

   /**
    * f0 -> "("
    * f1 -> StmList()
    * f2 -> ","
    * f3 -> Exp()
    * f4 -> ")"
    */
   public R visit(StmExp n, A argu);

}
