//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> StmList()
    * f1 -> <EOF>
    */
   public void visit(Goal n);

   /**
    * f0 -> Stm()
    * f1 -> ( ";" Stm() )*
    */
   public void visit(StmList n);

   /**
    * f0 -> Assignment()
    *       | PrintStm()
    */
   public void visit(Stm n);

   /**
    * f0 -> WriteId()
    * f1 -> ":="
    * f2 -> Exp()
    */
   public void visit(Assignment n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(WriteId n);

   /**
    * f0 -> "print"
    * f1 -> "("
    * f2 -> ExpList()
    * f3 -> ")"
    */
   public void visit(PrintStm n);

   /**
    * f0 -> Exp()
    * f1 -> ( AppendExp() )*
    */
   public void visit(ExpList n);

   /**
    * f0 -> ","
    * f1 -> Exp()
    */
   public void visit(AppendExp n);

   /**
    * f0 -> MulExp()
    * f1 -> ( PlusOp() | MinOp() )*
    */
   public void visit(Exp n);

   /**
    * f0 -> "+"
    * f1 -> MulExp()
    */
   public void visit(PlusOp n);

   /**
    * f0 -> "-"
    * f1 -> MulExp()
    */
   public void visit(MinOp n);

   /**
    * f0 -> PrimExp()
    * f1 -> ( MulOp() | DivOp() )*
    */
   public void visit(MulExp n);

   /**
    * f0 -> "*"
    * f1 -> PrimExp()
    */
   public void visit(MulOp n);

   /**
    * f0 -> "/"
    * f1 -> PrimExp()
    */
   public void visit(DivOp n);

   /**
    * f0 -> ReadId()
    *       | Num()
    *       | StmExp()
    */
   public void visit(PrimExp n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(ReadId n);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(Num n);

   /**
    * f0 -> "("
    * f1 -> StmList()
    * f2 -> ","
    * f3 -> Exp()
    * f4 -> ")"
    */
   public void visit(StmExp n);

}

